### ISSUE TITLE
Add support for `integer-gmp-1.0.0`

### ISSUE THREAD

**Issue by hvr** [cartazio/arithmoi#1]
see also #3

**Comment by snoyberg** [comment]
Bump, I need this for Stackage 7.10 support.

**Comment by peti** [comment]
We also needs these fixes for 7.10.x support in NixOS. The build currently fails as follows: http://hydra.cryp.to/build/740025/log/raw.

**Comment by hvr** [comment]
@peti strange, you shouldn't see that failure at all as the version bounds prohibit any install-plan for `arithmoi` involving `integer-gmp>=1` (at least I believe made sure of it by editing `.cabal` files)

**Comment by peti** [comment]
@hvr, you are right. We happily ignored those restrictions in our build, i.e. we compile with the NixOS equivalent of `--allow-newer`.

**Comment by peti** [comment]
Will this issue be fixed? Or is this package unmaintained?

**Comment by cartazio** [comment]
I've been buried with moving into a new apartment this month.  Will be getting to this and other PRs soon.  Aiming for this weekend.

**Comment by cartazio** [comment]
I welcome folks to help me finish moving apartments faster, but that's a
bit trickier than PRs ;)

**Comment by michaelt** [comment]
I'm not sure I follow everything, but fwiw, I built cyclotomic with Shea Levy's #3  branch using both ghc-7.10.1 and ghc-7.8.3 and nothing seems wrong so far.

**Comment by cartazio** [comment]
good to hear!
i'll be catching up on things and evaluating all the PRs soon. I've been
busy with moving this month and i'm still catching up on a huge stack of
OSS patches to merge and send out

**Comment by michaelt** [comment]
Sorry for the noise; that was nonsense. I just tested package as it comes with 'cabal install'; I compiled with with -fllvm but only just now tested it, with catastrophic results.

**Comment by crockeea** [comment]
When will this be pushed to hackage?

**Comment by cartazio** [comment]
probably later today
this week i'm on my first real vacation in a while, but finally have the
time to catchup on stuff :)

**Comment by cartazio** [comment]
ok, doing a pkg candidate now

**Comment by cartazio** [comment]
(pardon the delay, had a lot going on the past 1-2 months)

**Comment by cartazio** [comment]
@crockeea  @hvr @snoyberg 
https://hackage.haskell.org/package/arithmoi-0.4.1.3/candidate is the pkg candidate,
could you confirm it works for you before i push to hackage? (travis is green, but wanna make sure its all good :) )

**Comment by crockeea** [comment]
Worked for me Carter. Thanks for the update.
-Eric (crockeea)

**Comment by cartazio** [comment]
Should be uploaded and working.  Please confirm.

**Comment by crockeea** [comment]
Looks good to me.

**Comment by michaelt** [comment]
> factorise 32
     [(2,5)]

If I build with `-fllvm` but this may be a feature of my setup?

**Comment by cartazio** [comment]
1) the next major version of arithmoi is going to burn everything with fire
to improve the code quality
2) I'm moderately skeptical that llvm will actually make the code faster
given the total lack of benchmarks.
3) what ghc version and llvm version?

**Comment by michaelt** [comment]
The Glorious Glasgow Haskell Compilation System, version 7.10.1
        LLVM (http://llvm.org/): LLVM version 3.3  

I just mentioned `-fllvm` because it was an issue further up this thread, not because I have any particular hopes for it in this case. It's more than merely possible that my setup is botched anyway.  The standard non-llvm build is working fine, I built cyclotomic with it (this is what occasioned my drifting onto this issue) and it works fine.

**Comment by cartazio** [comment]
7.10 and 7.8 only support 3.5 llvm.  Any other llvm with those two ghc
versions will have problems. So your config is broken by construction :)

**Comment by michaelt** [comment]
Yes, that was what I was asking above. I am rebuilding.

**Comment by michaelt** [comment]
Ah, excellent yes, it builds, and simple programs like 

     main = print $ factorise 10000000000002

compile with -fllvm and work fine.

**Comment by michaelt** [comment]
Yes, -fllvm seems insignificant, whether it is applied to arithmoi or to dumb benchmarks, or both or neither.
