### ISSUE TITLE
Support Natural on the same level with Int, Word and Integer

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#100]
There are three "first-class" integer (implementing `Integral` instances) types in `arithmoi`: `Int`, `Word` and `Integer`. It means that polymorphic functions `Integral a => ...` has been written, keeping in mind only these three possibilities for `a`. Usually such functions get `{-# SPECIALISE #-}` or/and `{-# RULES #-}` to improve performance. Here is an example from `Math.NumberTheory.Powers.Squares`:

```haskell
integerSquareRoot :: Integral a => a -> a
integerSquareRoot n
  | n < 0       = error "integerSquareRoot: negative argument"
  | otherwise   = integerSquareRoot' n
{-# SPECIALISE integerSquareRoot :: Int -> Int,
                                    Word -> Word,
                                    Integer -> Integer
  #-}

integerSquareRoot' :: Integral a => a -> a
integerSquareRoot' = isqrtA
{-# RULES
"integerSquareRoot'/Int"     integerSquareRoot' = isqrtInt'
"integerSquareRoot'/Word"    integerSquareRoot' = isqrtWord
"integerSquareRoot'/Integer" integerSquareRoot' = isqrtInteger
  #-}
```

Further, such function are tested using `Math.NumberTheory.TestUtils.testIntegralProperty` to run each test thrice with different types.

Nowadays another integer type gains more traction: `Natural`, included in `base` since GHC 8.0. It represents non-negative integers of arbitrary size; `Natural` corresponds to `Integer` as `Word` corresponds to `Int`. We should support it through `arithmoi` on the same level with `Int`, `Word` and `Integer`.

There are three steps:

1. Check that polymorphic functions `Integral a => ...` are actually compatible with `Natural` arguments. This may be not the case, because (in contrast to `Word`) an attempt to create a negative `Natural` throws `Underflow :: ArithException`. 

E. g., `f x = (x - 1) + 2` is a perfectly valid function, when `x` is `Int` or `Integer` and even has an expected semantics for `Word`, but raises an exception on `x = 0 :: Natural`.

One can change `Math.NumberTheory.TestUtils` in the following way and adapt `testIntegralProperty`, `testSameIntegralProperty` and `testIntegral2Property` correspondingly. This should cover majority of cases, and other ones should be dealt manually. 

```diff
 type TestableIntegral wrapper =
-  ( Matrix '[Arbitrary, Show, Serial IO] wrapper '[Int, Word, Integer]
-  , Matrix '[Arbitrary, Show] wrapper '[Large Int, Large Word, Huge Integer]
+  ( Matrix '[Arbitrary, Show, Serial IO] wrapper '[Int, Word, Integer, Natural]
+  , Matrix '[Arbitrary, Show] wrapper '[Large Int, Large Word, Huge Integer, Huge Natural]
   , Matrix '[Bounded, Integral] wrapper '[Int, Word]
   , Num (wrapper Integer)
+  , Num (wrapper Natural)
   , Functor wrapper
   )
```

2. Add `{-# SPECIALISE #-}` pragmas to cover all four "first-class" integer types. This is the easiest, almost mechanical part of the task.

3. Add rewrite rules `{-# RULES #-}` and provide corresponding functions, benefiting from `Natural` arguments, where appropriate. May be easy, may be hard, may be superfluous.

**Comment by cartazio** [comment]
Number theory sans natural numbers is madness. Let’s dig into this!

**Comment by Bodigrim** [comment]
Tickets https://ghc.haskell.org/trac/ghc/ticket/14170 and https://ghc.haskell.org/trac/ghc/ticket/14465 have just been fixed in GHC master, meaning that from now on GHC Core supports `Natural` on the same level with `Integer`. This is an awesome improvement, closing a huge performance gap between these types.
