### ISSUE TITLE
Partition function

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#107]
[The partition function p(n)](https://en.wikipedia.org/wiki/Partition_(number_theory)#Partition_function) represents the number of possible partitions of a natural number n, which is to say the number of distinct ways of representing n as a sum of natural numbers (with order irrelevant). 

It would be nice to implement the partition function as a self-recurrent sequence `partition :: Num a => [a]` , using [the pentagonal number theorem](https://en.wikipedia.org/wiki/Pentagonal_number_theorem#Relation_with_partitions). The right place for it will be a new module `Math.NumberTheory.Recurrencies`.

**Comment by rockbmb** [comment]
@Bodigrim Hello;
Is it even possible to write `partition` as a self-recurrent sequence in an "efficient" way, as we would with e.g. `fibs = 0 : 1 : zipWith (+) fibs (tail fibs)`? Each value of `partition` requires an (at least) linearly growing number of previous results to compute, lists might not be helpful here.

**Comment by Bodigrim** [comment]
It depends on the definition of "efficient". Usually I start development with a vastly inefficient implementation (because it's better to have something than nothing), then cover it with tests and benchmarks and only after this proceed to all kinds of optimizations and improvements. 

In our case each element is a signed sum of some previous values. Mask of required values can be extracted in a linear time. This is better than quadratic time for naive indexing, but worse than O(n^1/2) for arrays.

**Comment by Bodigrim** [comment]
Here is an example of such function: 

```haskell
sumIndices :: Num a => [a] -> [Int] -> a
sumIndices = go 0 0
  where
    go :: Num a => a -> Int -> [a] -> [Int] -> a
    go acc _ _ [] = acc
    go _ _ [] is = error $ "sumIndices: indices not found " ++ show is
    go acc j (x : xs) is'@(i : is) = case i `compare` j of
      LT -> error $ "sumIndices: index not found " ++ show i
      EQ -> go (acc + x) (j + 1) xs is
      GT -> go acc       (j + 1) xs is'
```

E. g., 

```haskell
sumIndices [0..] [5, 7, 11] = 23
```

**Comment by Bodigrim** [comment]
I've been playing with my (unreleased yet) [`Data.Chimera`](https://github.com/Bodigrim/bit-stream/blob/master/Data/Chimera.hs), offering (almost) infinite lazy streams with O(1) indexing. 

Let us start from a pretty crazy function, vaguely resembling the recursion pattern of `partition`:

```haskell
foo :: Int -> Integer
foo 0 = 1
foo n = sum $ map foo $ indices n

indices :: Int -> [Int]
indices n = takeWhile (>= 0) $ map (\k -> n - k * k) [1..]
```

Computing `foo 50` takes 2 seconds on my machine, and anything above takes almost infinite time. One can cache values of `foo` into a list: 

```haskell
foo' :: [Integer]
foo' = 1 : map (\n -> sum $ map (foo' !!) $ indices n) [1..]
```

It is much faster. E. g., `foo' !! 10000` takes around 20 seconds. We can utilise `sumIndices` from above to improve running time further. 

```haskell
foo'' :: [Integer]
foo'' = 1 : map (\n -> sumIndices foo'' $ reverse $ indices n) [1..]
```

Now `foo'' !! 10000` completes almost instantly and, for instance, `foo'' !! 40000` takes around 24 seconds. But using [`Data.Chimera`](https://github.com/Bodigrim/bit-stream/blob/master/Data/Chimera.hs) lets us cut the time even further, almost 10x in comparison with `foo''`: 

```haskell
import Data.Chimera

foo''' :: [Integer]
foo''' = toList $ tabulateFix $ \f -> \case
  0 -> 1
  n -> sum $ map (f . fromIntegral) $ indices $ fromIntegral n
```

Here `foo''' !! 40000` takes 2.7 seconds.

**Comment by rockbmb** [comment]
@Bodigrim looks great, are you planning to release the package? I was considering a simple `{Int/Hash}Map` (or just `Map` first), although it'll make the `partition` list useless past its `maxBound :: Int`-th index.

**Comment by rockbmb** [comment]
@Bodigrim If you ever release your `bit-stream` package, please ping me so this can be refactored to use it.

**Comment by rockbmb** [comment]
@Bodigrim I don't mind benchmarking it to see if there's an improvement worth introducing an another dependency for.
