### ISSUE TITLE
Stackage

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#11]
What about publishing this package on Stackage?

**Comment by ppetr** [comment]
+1

**Comment by cartazio** [comment]
I'm hoping to do a serious overhaul of arithmoi soon, there's a number of
deep design issues and known bugs, but absolutely no test or benchmarking
coverage of the code base.

**Comment by cartazio** [comment]
There's also several known segafualts in really gnarly code that has no
bench marks or testing. So my medium term goal is to de-lower/"de
optimize " a lot of arithmoi code that has micro optimizations but zero
testing or benchmarks

**Comment by ppetr** [comment]
Maybe we could make a checklist of untested functions or modules. I'd be
happy to contribute a commit with a test occasionally, for example for
functions that I use.

Dne so 12. 12. 2015 19:11 uživatel Carter Tazio Schonwald <
notifications@github.com> napsal:

> There's also several known segafualts in really gnarly code that has no
> bench marks or testing. So my medium term goal is to de-lower/"de
> optimize " a lot of arithmoi code that has micro optimizations but zero
> testing or benchmarks
>
> On Saturday, December 12, 2015, Carter Schonwald <
> carter.schonwald@gmail.com>
> wrote:
>
> > I'm hoping to do a serious overhaul of arithmoi soon, there's a number of
> > deep design issues and known bugs, but absolutely no test or benchmarking
> > coverage of the code base.
> > On Dec 12, 2015 7:04 AM, "Petr Pudlák" <notifications@github.com

**Comment by cartazio** [comment]
Cool.  I'm hoping to use some vacation time end of the year to catchup on
my OSS backlog.  But yeah, arithmoi needs some serious test coverage work,
and that's gonna take a village.  I do have some serious concerns about how
the internals are designed, but testing work comes first.

**Comment by Bodigrim** [comment]
I'll be glad to help with tests and benchmarks. Which parts are most fishy?

**Comment by cartazio** [comment]
There are no tests at all except for the starting stub I think I pushed a
month or two ago.  I'll check when done with meetings later today

**Comment by Bodigrim** [comment]
IMHO it makes sense to review the purpose of low-level modules first. Many cavernous, difficult to test internals can be removed by switching to integer-gmp-1.0. 

E. g., latest integer-gmp already has both gcdInt and gcdWord, so there is no need in Math.NumberTheory.GCD.LowLevel. There are also functions for integer logarithms, which covers Math.NumberTheory.Logarithms. `testPrimeInteger` and its companions could replace `millerRabinV`. 

Also it maybe appropriate to split arithmoi into subpackages. For instance, Math.NumberTheory.Powers have nothing common with Math.NumberTheory.Primes, why should they be bundled together? They will be easier to manage when decoupled.

**Comment by cartazio** [comment]
depends on the algorithmic foundations

but yes, good point about taking advantage of the new GMP apis 

that said, closing this ticket for now because a LOT of testing work needs to happen before arithmoi gets a new release

**Comment by Bodigrim** [comment]
@ppetr it would be great, if you write tests for functions, which you use. I have almost covered with tests everything else but `Math.NumberTheory.Primes`, but `Primes` still remains a bulwark of bugs.
