### ISSUE TITLE
Dirichlet beta function

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#117]
[Dirichlet beta function](https://en.wikipedia.org/wiki/Dirichlet_beta_function) is an important analogue of Riemann zeta function, implemented in #44. Beta function is especially handy when it comes to analytic number theory over Gaussian integers. 

It would be nice to compute its values at positive integer points, similar to Riemann zeta function in [Math.NumberTheory.Zeta](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/Zeta.hs).

**Comment by rockbmb** [comment]
@Bodigrim have you read [this](https://arxiv.org/pdf/0910.5004.pdf) paper before? From it, it seems someone in the OEIS wiki derived a [handy](https://oeis.org/wiki/Dirichlet_beta_function#Formulae) (see the equality for `β(2n)`) formula for the function.

**Comment by rockbmb** [comment]
What would the issue with the polygamma function `ψ` be? There's [this](https://en.wikipedia.org/wiki/Polygamma_function#Recurrence_relation) recurrence (see first equation in the "Recurrence relation" section) that doesn't seem too bad.

**Comment by Bodigrim** [comment]
The formula above involves growing derivatives of polygamma function at fixed argument 1/4, not a fixed derivative of growing arguments.

**Comment by rockbmb** [comment]
Yes, nevermind - I just noticed that recurrence is only valid for positive integers.

**Comment by rockbmb** [comment]
Found [this](http://www.emis.ams.org/journals/JIS/VOL4/CHEN/AlgBE2.pdf) for Euler numbers, check the last page. A little confusing because the author uses `[x]` to mean `⌊x⌋ = floor x`.

**Comment by rockbmb** [comment]
@Bodigrim regarding formula (57) from [Computational strategies for the Riemann zeta function](https://cr.yp.to/bib/2000/borwein.pdf), do you find it worthwhile add something to `zetas`'s documentation that describes the algebraic manipulations undertaken to get the formula from how it was presented to what is shown in the code? Perhaps a link to a GitHub gist with some LaTEX.

I'm about to do the same for formula (12) from [An Euler-type formula for β(2n) and closed-form
expressions for a class of zeta series](https://arxiv.org/pdf/0910.5004.pdf) and the only real record of it will be the paper I write in, which is not ideal.

**Comment by Bodigrim** [comment]
I wonder if it is feasible to use Literate Haskell here to combine code and LaTeX explanations.

**Comment by rockbmb** [comment]
Definitely, although the reason I did not want to inline LaTeX is because it'll get extremely unwieldy since these expressions are quite complicated.
