### ISSUE TITLE
Eisenstein integers

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#118]
My feeling is that currently #73 is too broad and too vague. We should rather explore more special cases to hone API before taking a stab at the general problem. 

We have already implemented the simplest quadratic ring, which is the ring of [Gaussian integers](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/GaussianIntegers.hs). The next step is to handle the ring of Eisenstein integers. 

The API may follow the outline of [Math.NumberTheory.GaussianIntegers](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/GaussianIntegers.hs). Required mathematical background can be found here:
* https://en.wikipedia.org/wiki/Eisenstein_integer
* https://en.wikipedia.org/wiki/Eisenstein_prime

**Comment by rockbmb** [comment]
Sounds like an interesting issue, I'll put this in my TODO list.
