### ISSUE TITLE
Use Chudnovsky rational approximation of pi^2 for zetasEven

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#123]
To evaluate Riemann zeta function on even arguments (`zetasEven`) we use formula:
![image](
https://wikimedia.org/api/rest_v1/media/math/render/svg/1620b1201ba2d4d6472301cf6ee7b6df649fce4f)
The main issue here is that for reasonably big `n` we divide one huge number by another one, meaning a catastrophic loss of precision. For instance, 

```haskell
> approximateValue (zetasEven !! 25) :: Double
0.9999999999999996
> approximateValue (zetasEven !! 999) :: Double
NaN
```

which does not make any sense, because the zeta function is always finite and `> 1`. Currently we fix this behaviour by flooring values of `zetasEven` by 1.

This discrepancy hurts evaluation of Riemann zeta function on odd arguments and propagates further to numeric errors in Dirichlet beta function.

---

This is a rough idea, I have not given it much thought.

[Chudnovsky algorithm](https://en.wikipedia.org/wiki/Chudnovsky_algorithm) gives us a rapidly converging series of rational approximations to `pi^2`. We can use it to generate a rational approximation of `zetasEven !! n` and consequently calculate not only `zetaEven !! n` itself (which is any way close to 1), but also `zetasEven !! n - 1` using usual `Double` with a fairly good **relative** precision.

**Comment by b-mehta** [comment]
Surely the issue here is in `approximateValue` from ExactPi, rather than in `zetasEven`? Specifically, `zetasEven` returns an exact value, and the loss of precision occurs when converting the exact value into a Double.

**Comment by rockbmb** [comment]
:+1: for loss of precision in Dirichlet beta. The code introduced by #120 works, but not very well. Error propagation from `zetasOdd` and `zetasEven` is quite strong.

**Comment by Bodigrim** [comment]
Cool! 

@b-mehta do you know any rapidly converging rational series for `pi`? If yes, then we could possibly combine it with Chudnovsky algorithm for `pi^2` and squeeze them together into `exact-pi` instead of [Data.ExactPi. rationalApproximations](https://github.com/Bodigrim/exact-pi/blob/master/src/Data/ExactPi.hs#L103).

**Comment by b-mehta** [comment]
@Bodigrim I don't know of any off the top of my head, but I'll research. In the meantime, I've just pushed to b-mehta/arithmoi@23b385d for a solution which should work if the answer turns out to be no: I've made a datatype `ExactPiSq` as a simple analogue to `ExactPi` along with a new `approximateValue` which uses Chudnovsky's algorithm to get the best approximation for a given Fractional instance.  

The test value in the docs for zeta(50) used to differ from the true value after only around 10 non-zero places, but now agrees to a Fixed Prec50 at least. In addition, we can now get values for `zetasEven !! n-1` as you mentioned ([cf WolframAlpha](http://www.wolframalpha.com/input/?i=zeta(100)+-+1)):

```
> import Data.Number.Fixed
> let Exact z q = zetasEven !! 50
> approximateValue (Exact z q) :: Fixed Prec50
1.00000000000000000000000000000078886090522101180736
> getRationalLimit [q * p^z - 1 | p <- chudnovsky]
7.888609052210118e-31
```

**Comment by b-mehta** [comment]
One possible solution would be to use Chudnovsky's algorithm directly, and use a rational approximation to the square root using continued fraction convergents which is easy to calculate and should be fairly easy to accelerate also.

**Comment by Bodigrim** [comment]
Looks awesome! 

The approach with rational approximation to the square root sounds reasonable. 

I suggest passing comparison function `a -> a -> Bool` to `getRationalLimit` as an argument and do not rely on `Eq` instance. This is not only more flexible in terms of precision, but is also a cure against `NaN /= NaN` thing, which is a common reason for fix-point evaluations cycling forever.

**Comment by b-mehta** [comment]
Sounds good, I'd like to do some numerical testing myself before making changes in `exact-pi`, but the modifications to `getRationalLimit` sound good. Would it be better to move the Chudnovsky work here to that repo instead?

**Comment by Bodigrim** [comment]
Yes, IMHO Chudnovsky algorithm itself fits into `exact-pi` better.

**Comment by Bodigrim** [comment]
Yes, if nothing happens I will proceed with my fork.

**Comment by Bodigrim** [comment]
I managed to upload `exact-pi-0.5.0.0` with @b-mehta's improvements to `rationalApproximations`.

**Comment by rockbmb** [comment]
The issue has been merged, I'm guessing we can proceed with a PR to improve `zetas`.

**Comment by Bodigrim** [comment]
I patched `arithmoi` to benefit from `rationalApproximations`. It has an immediate effect even for `Double`. For example, `betas 1e-15 !! 31` gives a correct value of 0.9999999999999983 instead of 0.9999999999999976 previously.

@b-mehta thanks for valuable contribution!

**Comment by rockbmb** [comment]
@Bodigrim That's great. Thanks for doing the change yourself.
