### ISSUE TITLE
Modular equations

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#129]
Provide high-level functions to solve linear and quadratic equations by modulo. 

Implement `solveLinear` satisfying `propLinear` and `solveQuadratic` satisfying `propQuadratic`.

```haskell
solveLinear :: Mod m -> Mod m -> [Mod m]
solveLinear = undefined 

propLinear :: Mod m -> Mod m -> Bool 
propLinear a b = 
  all 
    (\x -> (a * x + b == 0) == x `elem` solutions) 
    [minBound .. maxBound]
  where 
    solutions = solveLinear a b

solveQuadratic :: Mod m -> Mod m -> Mod m -> [Mod m]
solveQuadratic = undefined 

propQuadratic :: Mod m -> Mod m -> Mod m -> Bool 
propQuadratic a b c = 
  all 
    (\x -> (a * x ^ 2 + b * x + c == 0) == x `elem` solutions) 
    [minBound .. maxBound]
  where 
    solutions = solveQuadratic a b
```

Applications: `solveLinear` can be used instead of `solveCongruence` in #110, `solveQuadratic` may be used to solve `norm (z :+ 1) == 0` in quadratic fields (Gaussian, Eisenstein, etc.) for purposes discussed in #111.

**Comment by Bodigrim** [comment]
I'll assign myself to this issue.

**Comment by b-mehta** [comment]
@Bodigrim For efficient implementation of `solveQuadratic` for prime powers, Hensel's lemma is likely a good approach (and of course for other composites, the Chinese remainder theorem will reduce the problem to this case).
