### ISSUE TITLE
 Not in scope: type constructor or class ‘Word64’

### ISSUE THREAD

**Issue by ppetr** [cartazio/arithmoi#13]
I had problems when compiling the package, getting this error for a few files.

- GHC version: 7.10.2
- cabal version:1.22.6.0, cabal library 1.22.4.0
- environment: (stackage-lts-3.17)[http://www.stackage.org/lts-3.17]
- System: 32-bit Debian Linux

The diff below fixed the problem for me, although it's probably not an universal solution:
```diff
diff --git a/Math/NumberTheory/Moduli.hs b/Math/NumberTheory/Moduli.hs
index 1daa9e0..29390d5 100644
--- a/Math/NumberTheory/Moduli.hs
+++ b/Math/NumberTheory/Moduli.hs
@@ -42,6 +42,7 @@ import Data.Array.Unboxed
 import Data.Array.Base (unsafeAt)
 import Data.Maybe (fromJust)
 import Data.List (nub)
+import Data.Word
 import Control.Monad (foldM, liftM2)
 
 import Math.NumberTheory.Utils (shiftToOddCount, splitOff)
diff --git a/Math/NumberTheory/Primes/Sieve/Eratosthenes.hs b/Math/NumberTheory/Primes/Sieve/Eratosthenes.hs
index f57f629..d094dad 100644
--- a/Math/NumberTheory/Primes/Sieve/Eratosthenes.hs
+++ b/Math/NumberTheory/Primes/Sieve/Eratosthenes.hs
@@ -42,9 +42,9 @@ import Data.Array.ST
 #endif
 import Control.Monad (when)
 import Data.Bits
-#if __GLASGOW_HASKELL__ < 709
+-- #if __GLASGOW_HASKELL__ < 709
 import Data.Word
-#endif
+-- #endif
 
 import Math.NumberTheory.Powers.Squares (integerSquareRoot)
 import Math.NumberTheory.Utils
```

----

I also got a bunch of warnings like
```
Math/NumberTheory/Primes/Sieve/Misc.hs:153:93: Warning:
    Literal 3737841677 is out of the Int range -2147483648..2147483647
```
It's probably ok, but it'd be nice to avoid them so that people don't get scared something is broken :)

**Comment by cartazio** [comment]
Huh, I'll look into it when I get arithmoi to the top of my queue.
Arithmoi as it currently stands has a lot of design debt, and I didn't
quite realize how much till I took over maintainership.

**Comment by Bodigrim** [comment]
Imports should have been fixed by #10 and #26. 
@ppetr could you please confirm? Or anyone else with GHC >= 7.10 and 32-bit?

**Comment by errge** [comment]
I confirm that the current git head builds with ghc 7.10.3 in 32-bit intel.

**Comment by Bodigrim** [comment]
Nice.

**Comment by ppetr** [comment]
Sorry for being unresponsive, thanks for fixing it!

pá 15. 4. 2016 v 18:14 odesílatel Bodigrim <notifications@github.com>
napsal:
