### ISSUE TITLE
Integrate doctests

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#134]
There are `doctest` examples in haddock documentation here and there. It would be nice to test their correctness automatically, because otherwise they quickly fall out of sync.

**Comment by rockbmb** [comment]
Perhaps this can be a step that is added to CI before or after `cabal (new-)test` is run.

**Comment by Bodigrim** [comment]
It is difficult to say, but I tend to release twice a year. So if nothing changes, next release is April 2019.

**Comment by Bodigrim** [comment]
It seems that we would not be able to incorporate `doctests` into a regular test suite. Several modules of `arithmoi` use `{#- LANGUAGE UnboxedTuples -#}`, which is incompatible with `ghci`. And since `doctests` uses `ghci` to run snippets, it cannot process the vast majority of modules.

I managed to run `doctests` by temporarily removing `{#- LANGUAGE UnboxedTuples -#}` and fixed most of mismatches.
