### ISSUE TITLE
Smooth Gaussian and Eisenstein numbers

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#137]
We say that the number `n` is `B`-smooth if `n` can be represented as a product of powers of elements of a set `B`. Module `Math.NumberTheory.SmoothNumbers` contains functions to deal with smooth numbers. It currently supports `Integral` types only. It would be nice to extend this notion to any `Eucledian` type, including `GaussianInteger` and `EisensteinInteger`. 

The main issue is that there is no natural order on `GaussianInteger`, so it is impossible for `smoothOver` to return smooth numbers in ascending order. For the same reason we cannot have `smoothOverInRange` or `smoothOverInRangeBF`, because for an arbitrary `Eucledian` there is no natural definition of a range.

I expect that we need define two new functions. 

1. Define 

```
smoothOver' 
  :: (Euclidean a, Ord b)
  => (a -> b)
  -> SmoothBasis a 
  -> [a]
smoothOver' norm basis = undefined
```

which outputs numbers, smooth over `basis`, in an ascending order determined by user-supplied `norm`. Then define `smoothOver = smoothOver' abs`.

2. Define 

```
isSmooth
  :: Euclidean a 
  => SmoothBasis a 
  -> a 
  -> Bool
```

and express `smoothOverInRangeBF` via it.

Reference: https://en.wikipedia.org/wiki/Smooth_number

**Comment by rockbmb** [comment]
Sounds interesting, I'll take a look.

**Comment by rockbmb** [comment]
@Bodigrim it seems `smoothOverInRangeBF` requires an `Enum` instance, which can't be sensibly defined for `Gaussian/EisensteinInteger`. Unless they're restricted to the first quadrant/sextant, respectively.

**Comment by Bodigrim** [comment]
True, `smoothOverInRange` will remain constrained by `Integral a`. But one will be able to filter a list of `GaussianInteger` (for instance, rectangle or circle on a complex plane) by `isSmooth`.

(Actually, I've been thinking to deprecate `smoothOverInRangeBF` once we have `isSmooth`).
