### ISSUE TITLE
Factorisation including units

### ISSUE THREAD

**Issue by b-mehta** [cartazio/arithmoi#139]
Is it possible to have something like 
```
factorise' :: UniqueFactorisation a => a -> ([(Prime a, Word)], a)
```
for which the second argument is the remaining unit, with the invariant

```
unit * product (map (\(p,k) -> unPrime p ^ k) powers) == n
  where (powers, unit) = factorise' n
```

and ```snd (factorise' n)``` is always a unit?

The invariant for `factorise` is significantly weaker, since `3+4i` and `5` have the same absolute value in the Gaussian integers, but ought to have different factorisations, so just checking that
```
abs n == abs (product (map (\(p, k) -> unPrime p ^ k) (factorise n)))
```
seems disappointing for domains with possibly non-real parts.

In addition, it would be nice to have that `factorise'` has a right inverse, and one could reconstruct a number from its factorisation.

**Comment by Bodigrim** [comment]
It is true that `norm 5 == norm (3 + 4i)`, but `abs 5 /= norm (3 + 4i)`.

**Comment by b-mehta** [comment]
Ah fair point, my mistake. I still feel like this may be a valuable function in any case.

**Comment by Bodigrim** [comment]
Do you have any particular use case in mind? In my personal experience such function was rarely needed.

**Comment by rockbmb** [comment]
If the unit is necessary, can't one just do

```
let (powers, unit) = (factorise n, signum n)
in ...
```

since `factorise = factorise . abs`?

**Comment by b-mehta** [comment]
That approach sounds reasonable - seems like I didn't think this through well enough. Thanks both.

**Comment by Bodigrim** [comment]
Even if `n == abs n`, it is not guaranteed that `product (map (\(p, k) -> unPrime p ^ k) (factorise n) == n`. For example, take `n = 2 :: GaussianInteger`. We have `factorise n = [(Prime 1+ι,2)]`, but `(1+ι)^2 = 2*ι /= 2`.

**Comment by b-mehta** [comment]
@rockbmb Right - my initial concern had been that this approach requires actually computing the product again which could be more costly than necessary if `factorise` throws away the unit information anyway.

@Bodigrim I don't have a use case in mind, it just struck me as odd that the units were thrown away, given that the statement of unique factorisation I'm used to gives something like `n = u p1^k1 ... pi^ki`.

**Comment by Bodigrim** [comment]
For `Int`/`Word`/`Integer`/`Natural` one can just take `signum` of an argument, as pointed above by @rockbmb. It is true that things get more complicated for quadratic fields, but here tracking of units is not actually free of charge, it makes factorisation algorithm more involved. I believe that for most of applications one can spend time reconstructing the product back.
