### ISSUE TITLE
Spelling Bug in Module Name Math.NumberTheory.Recurrencies

### ISSUE THREAD

**Issue by CarlEdman** [cartazio/arithmoi#144]
While "currency" pluralizes to "currencies," "recurrence" pluralizes to "recurrences."  See [Wiktionary](https://en.wiktionary.org/wiki/recurrence).  English is not my native language, so whoever misspelled this has not only my sympathy but shared pain at the intricacies of English spelling.

That said, a fix, if deemed worthwhile, should probably keep the old modules around, just importing and re-exporting the original content with some depreciation warning for some time.

**Comment by rockbmb** [comment]
It'll be a little painful to keep two versions of the same module around... Thanks for the heads-up!

**Comment by Bodigrim** [comment]
This is my fault, thanks for reporting :)
Yes, I believe re-exporing is a way to go, even if painful.
