### ISSUE TITLE
Order of primes in factorise

### ISSUE THREAD

**Issue by CarlEdman** [cartazio/arithmoi#161]
I realize now that this is not actually stated in the documentation, but I always assumed that the primes would be listed in ascending order as they are almost always.  However:

```
Prelude Math.NumberTheory.Primes.Factorisation> factorise 10251562501
[(101701,1),(100801,1)]
it :: [(Integer, Int)]
(0.00 secs, 1,321,416 bytes)
```

Is that intended?  Running arithmoi 0.8 on Haskell Platform 8.6.3.

**Comment by Bodigrim** [comment]
Yes, it is intended. Otherwise one cannot factor huge numbers in a lazy fashion, e. g., `head . factorise`.

**Comment by CarlEdman** [comment]
If there is an advantage to it, let's keep them returning in non-ascending order.  But perhaps it could be mentioned in the docs that the order of prime factors, while almost always ascending, this is not guaranteed. 

I'm a pretty heavy arithmoi user and I didn't know that and hence spent two days tracking down a bug in my code ultimately due to the fact that ```fst.last.factorise``` is not a valid way to find an integer's largest prime factor.  Rather, in rare cases one one needs ```foldl' max 0.map fst.factorise```

**Comment by Bodigrim** [comment]
Sure, it is a good idea to clarify this in docs, thanks for suggestion. Sorry for your troubles.

Small factors below 100000 are found by trial division and thus are always ordered. But when it comes to factorisation over elliptic curves, the order of factors becomes unpredictable. So factors become unsorted only when there are at least two sufficiently big prime factors.
