### ISSUE TITLE
Add divisorCount as a synonym for tau

### ISSUE THREAD

**Issue by erantapaa** [cartazio/arithmoi#162]
Even though I use this library a lot I keep on forgetting to use the `tau` function to get the number of divisors of a number.

The index lists a host of functions related to the divisors a number, but it's not clear that it has a divisor count function. I suggest adding a function called `divisorCount` so that this capability may be easily discovered.

**Comment by Bodigrim** [comment]
Totally makes sense. Do you know how is this function named in other languages/libraries/platforms? Should it be `divisorCount` / `countDivisors` / `numberOfDivisors` / etc.?

**Comment by Bodigrim** [comment]
Done, thanks for suggestion.
