### ISSUE TITLE
Separate Euclidean to its own package

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#166]
Type class `Integral`  is completely messed up. 

```haskell
class (Real a, Enum a) => Integral a where 
  toInteger :: a -> Integer 
  quotRem   :: a -> a -> (a, a)
  ...

class (Num a, Ord a) => Real a where 
  toRational :: a -> Rational 
```

First of all, `Real` constraint looks really weird. How is it connected to being `Integral`? 

Having both `toInteger :: a -> Integer` and `Num.fromInteger :: Integer -> a` means that `a` is isomorphic to a subset of `Integer`.

(Moreover, `Enum.toEnum :: a -> Int` and `Enum.fromEnum :: a -> Int` imply that `a` is no greater than `Int`, which is untrue even for `Integer` and `Natural`, but who cares).

This is very restrictive, because there are many rings, larger than `Integer`, where one can still define a sensible `quotRem`. And having `quotRem` is enough for `gcd`, `lcm`, etc. Obvious example is a ring of polynomials, together with its factor rings (Gaussian integers, Eisenstein integers, etc.).

For the reasons above @rockbmb and I developed a type class `Euclidean` (https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/Euclidean.hs), representing [Euclidean domains](https://en.wikipedia.org/wiki/Euclidean_domain). It is basically `Integral` without `toInteger`:

```
class (Eq a, Num a) => Euclidean a where 
  quotRem   :: a -> a -> (a, a)
  ...  
```

It is used extensively throughout `arithmoi` for [quadratic integers](https://en.wikipedia.org/wiki/Quadratic_integer). 

--- 

I want to use `Euclidean` for polynomials in https://github.com/Bodigrim/poly, but `arithmoi` itself is a quite heavy dependency. So my intention is to extract it into a dedicated package.

**Comment by Bodigrim** [comment]
@chessai does it look like `Euclidean` might find a new home in `semirings`? It has the same kind of relation to `Integral` as `Semiring` has to `Num` :) IMO it is a natural point in a practical design of numeric hierarchy. E. g., `class (Eq a, Ring a) => Euclidean a`.

**Comment by chessai** [comment]
To me this looks good. A Real constraint is so weird, as you say. I'd be willing to take a PR. Though, per the context of our other discussion, if this was in semirings, we'll probably not ever remove Ring.

**Comment by cartazio** [comment]
Enum is busted too... :)

**Comment by cartazio** [comment]
@chessai i suspect the historical origin of the Real constraint has to do with either complex integers and or having ord implied as another constraint?

**Comment by chessai** [comment]
> @chessai i suspect the historical origin of the Real constraint has to do with either complex integers and or having ord implied as another constraint?

This makes a lot of sense.
