### ISSUE TITLE
Segmentation fault with primeList and primeSieve

### ISSUE THREAD

**Issue by mietek** [cartazio/arithmoi#2]
Reported by @treeowl ([dafis/arithmoi#16](https://bitbucket.org/dafis/arithmoi/issue/16/segmentation-fault-with-primelist-and)).

To reproduce:

```
$ cabal sandbox init
$ cabal install arithmoi-0.4.1.1 hspec-2.1.2 --ghc-options=-fasm
$ cat >Spec.hs <<'EOF'
```
```haskell
import Test.Hspec
import Test.QuickCheck
import Math.NumberTheory.Primes

primesSumWonk :: Int -> Int
primesSumWonk upto = sum . takeWhile (< upto) . map fromInteger . primeList $ primeSieve (toInteger upto)

primesSum :: Int -> Int
primesSum upto = sum . takeWhile (< upto) . map fromInteger $ primes

main = do
  hspec $
    describe "Primes.primesSumWonk" $
      it "works like primesSum" $
        property $ \n -> let upto = abs (n `rem` 45)
                         in primesSum upto == primesSumWonk upto
````
```
EOF
$ cabal exec runhaskell Spec.hs

Primes.primesSumWonk
Segmentation fault (core dumped)
```

@treeowl adds:

> FYI, if you do decide to attempt to fix this, you might look at making it use the `bitvec` package for mutable bit vectors instead of weaving that junk into the prime sieve in a way that leaves me utterly baffled about just what it's supposed to be doing. Another very pleasant alternative might be to just steal sieves from the `NumberSieves` package. I have no idea about how their performance compares, theoretically, but anything is better than code that's blatantly _broken._

**Comment by treeowl** [comment]
FYI, specializing the `NumberSieves` code to `Word` (to unbox the heap) and such improves performance a good bit. I think it can be improved further using a vector-based heap implementation, but the details are a bit tricky.

**Comment by cartazio** [comment]
1) can you, david or mietak, do a PR starting  a test suite using hspec
with this as the first test? I was dreading the lack of tests, now we
know!  Probably the first big task is getting some decent unit test
coverage

2) I'll look at this more after im lucid,

**Comment by treeowl** [comment]
I don't know if I'll have time for that soon. One problem is that the test does not *always* go boom. The correct solution to that is to make the test build use only checked vector operations. This should come closer to guaranteeing that a bad index will make the test fail, and fail in a somewhat less horrifying way.

**Comment by cartazio** [comment]
Gotcha.  I'll get on it
