### ISSUE TITLE
curveFactorisaton : quirk with selecting "parms"

### ISSUE THREAD

**Issue by grandpascorpion** [cartazio/arithmoi#23]
Hi,

In the internal sub-function "fact" in curveFactorisation in Math/NumberTheory/Primes/Factorisation/Montgomery.hs, there's this line:

mult j <$> fact k (if null pfs then digs+4 else digs)

digs = # of digits and is passed to findParms to return B1, B2 and curve count.
Looks a little awkward, I think it should be incrementing it so that it grabs the next tier.  (For instance, jumping from 15 to 20).    

When factoring a number, it looks like you would see this pattern due to the varying differences between tiers:
8,   12, 16, 20, 24(_), 28, 32, 36, 40, 44 (_)  -- num digits checked in findParms
12, 15, 20, 25, 25,    30, 35, 40,  45, 45     -- "tier" found in testParams
- means that that digit-tier would be executed twice which is clearly incorrect.

For a quick fix, we could change the hard-coded 4
to a conditional: (if digs <= 16 then 4 else 5)

This "jump of 4" logic is also present in the certiFactorisation function.

**Comment by Bodigrim** [comment]
I must confess that I do not know `Montgomery.hs` deeply enough to verify your proposal at a glance. IMHO we have to annotate the algorithm with comments, cover it with tests and benchmarks before making any changes in logic. If you came to know the particulars of the algorithm, could you please write comments and make pull request?

From the other side, I am certain that hardcoded table of B1, B2, CC is a wrong practice. As it was discussed in #21, the real solution is to have a formula to compute them for any number of digits and get rid of tabulated tiers.

**Comment by grandpascorpion** [comment]
Hi Andrew,

No worries, I'm not an expert myself.

One key section from
http://www.mersennewiki.org/index.php/Elliptic_Curve_Method sheds some
light:

... As described above it probably sounds a bit of a hit-or-miss affair,
but there are controls built into the programme. By carefully determining
the starting values for the programme it is possible to limit our search to
factors of no more than some size measured in bits (a bit is the smallest
unit of computer memory). After running the requisite number of curves
(detailed on a table on this page) at one particular bit level, we can then
start to look for factors at a higher bit level. Even at the higher bit
level it is still possible to find factors of the smaller size.
 I realize this will sound anecdotal but ... from www.mersenneforum.org, I
know that people would attack a particular problem in groups by curve
count.  Say we had a large composite number, a person might try to run the
recommend number of curves for each digit tier (with the recommended B1, B2
values) and then announce they have run the recommended number of curves
for each tier though 40 digits (for example).  I might respond and say I
will try running curves at 45-digit tier.  After a few days, I'll respond
that I have run 1000 curves for that tier.  (For 45 digits, the number of
curves is 10600).  Say after a week, collectively people have indicated
they have run 11k curves (with no success).  At that point, the original
poster might suggest that we move onto the 50 digit tier.

(Hence, the increment by 4 looks quite fishy if it results in a "tier"
being run twice.  It's not too bad for the 25-tier but it's potentially
quite wasteful for the 45-tier)

So, I think it's necessary to do it by tiers but I agree that B1, B2 and CC
need to be optimized for the implementation.
(I'm not sure if it makes sense to do it all on the fly each time though.)

Speaking of magic numbers in the code, I saw there were some others in the
montgomeryFactorisation routine.  It would be nice to have a comment for
them.  Quick search didn't reveal anything.

----------------------------
Kind of a tangent, but do you know if anyone considered a way to
parallelize the curve checking?

-Fred

On Wed, Mar 16, 2016 at 2:44 PM, Andrew Lelechenko <notifications@github.com

**Comment by Bodigrim** [comment]
> Kind of a tangent, but do you know if anyone considered a way to
> parallelize the curve checking?

In theory it is not difficult: just run `workFact` over a rolling buffer of curves (`parBuffer` from `Control.Parallel.Strategies`). Practically we need to disentangle and decouple `curveFactorisation` to make `workFact` more accessible.

**Comment by Bodigrim** [comment]
Closed in #65.
