### ISSUE TITLE
GHC-8.0 compatible release

### ISSUE THREAD

**Issue by phadej** [cartazio/arithmoi#28]
AFAICS the `master` branch builds ok with GHC-8.0.1. The Hackage version has restrictive bounds though (`ghc-prim < 0.5`).

**Comment by cartazio** [comment]
Derp, yeah, modigrim and I have that planned. I need to write up some
release notes and stuff but thanks for Remindinf me.  My oss / work queue
has been a bit nutty.

Many many thanks for reminding me. I'll schedule some time this afternoon
to do the notes

**Comment by Bodigrim** [comment]
I have created PR #29 
@cartazio could you please sign off?

**Comment by cartazio** [comment]
Will get on it after I wake up :)

**Comment by Bodigrim** [comment]
Fixed in #29. Release 0.4.2.0 is available from Hackage and is compatible with GHC 8.0.

**Comment by phadej** [comment]
Thanks!

**Comment by cartazio** [comment]
announce done :)

**Comment by cartazio** [comment]
@Bodigrim the change log does'nt mention 7.10 support in the version range, ... which range are we supporting for this release? :''''/ (i presuem 7.8-8.0, but i forget)

**Comment by Bodigrim** [comment]
Oh, mea culpa. 7.10 is supported too, of course.

**Comment by Bodigrim** [comment]
```
tested-with         : GHC==7.6.3, GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
```

**Comment by cartazio** [comment]
Cool :)

I amended the Reddit post to clarify ;)

Satisfactory announce text I hope? I hope you enjoyed the mutiplicative bit
:)

**Comment by Bodigrim** [comment]
Yeah, great announce :) Thank you very much.
