### ISSUE TITLE
New release of `arithmoi`

### ISSUE THREAD

**Issue by phadej** [cartazio/arithmoi#40]
Can the current `master` be released to Hackage. It will help with Stackage's https://github.com/fpco/stackage/issues/1691 going forward (we don't want to disable tests!)

Btw, I checked that `master` is supports all recent versions of other dependencies as well.

**Comment by Bodigrim** [comment]
Are there any other upper bounds to bump?

**Comment by phadej** [comment]
@Bodigrim from my pov everything looks good.

**Comment by Bodigrim** [comment]
Cool. I am for it. I can prepare changelog tomorrow. cartazio?

**Comment by cartazio** [comment]
Sorry for the lag.
Sure. Would this be a minor version or bug fix release atm? Or would it
need be a major version?

**Comment by Bodigrim** [comment]
IMHO since we add new functionality, but do not remove old one, it can be a minor release: 0.4.2.0 -> 0.4.3.0. I'll prepare a pull request.

**Comment by Bodigrim** [comment]
@phadej arithmoi 0.4.3 has been released and uploaded onto Hackage. Please let me know if it plays well with Stackage.

**Comment by Bodigrim** [comment]
Closed after successful merge of fpco/stackage#1889
