### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [cartazio/arithmoi#42]
The documentation for the latest version of this package is missing on Hackage. They've been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by Bodigrim** [comment]
It seems that my `cabal` does not support `--doc` option.

```
$ stack exec cabal -- upload --doc
cabal: unrecognized 'upload' option `--doc'

$ stack exec cabal -- --version
cabal-install version 1.22.7.0
using version 1.22.7.0 of the Cabal library

$ stack exec cabal -- upload --help
Uploads source packages to Hackage.

Usage: cabal upload [FLAGS] TARFILES

Flags for upload:
 -h --help              Show this help text
 -v --verbose[=n]       Control verbosity (n is 0--3, default verbosity level
                        is 1)
 -c --check             Do not upload, just do QA checks.
 -u --username=USERNAME Hackage username.
 -p --password=PASSWORD Hackage password.
```

Should I use a newer version of `cabal`?

**Comment by expipiplus1** [comment]
I think that this was introduced in 2.24.

**Comment by Bodigrim** [comment]
Hmm. In any case Hackage finally managed to build docs on 26th of October.

**Comment by cartazio** [comment]
Also use up to date cabal rather than stack :)
