### ISSUE TITLE
once random v2 is out, make sure arithmoi can use it/ benefits from it

### ISSUE THREAD

**Issue by cartazio** [cartazio/arithmoi#47]

**Comment by cartazio** [comment]
@Bodigrim  :)

**Comment by Bodigrim** [comment]
Cool, will do :)

**Comment by Bodigrim** [comment]
Depends on https://github.com/haskell/random/issues/31

**Comment by rockbmb** [comment]
Has anything changed with this issue? I see here that haskell/random#31 is still open.

**Comment by Bodigrim** [comment]
I am keen to close this issue, because there are no action points. When `random-2.0` will be available, we'll definitely see if anything is broken and requires fixing. In fact, since `arithmoi` makes only a shallow use of random numbers, I expect that it will be still compatible.

**Comment by cartazio** [comment]
There’s gonna be 1-2 breakages but I’ll be doing a release pretty shortly.
Got it mostly done New Year’s Eve. But yeah any breakages will be obvious.

The core breakages will be improving perf, quality and reproducibility

**Comment by cartazio** [comment]
But yeah. Close at your leisure.  The release will be noticeable.

**Comment by Bodigrim** [comment]
Great!
