### ISSUE TITLE
Polymorphic fibonacci/lucas

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#61]
Currently `Math.NumberTheory.Recurrencies.Linear` exposes monomorphic functions `fibonacci`, `fibonacciPair`, `lucas`, `lucasPair`, `generalLucas`, which return `Integer` values. This is not suitable for some scenarios. 

For instance, recently I needed a Fibonacci number with index `10^15` modulo `123456789`. The Fibonacci number itself is eminently huge, but, since modulo is small, the reduced value should be computable in a blink of an eye. If `fibonacci` function would be polymorphic by return value, allowing any `Num`, I could specify `Mod 123456789` as a type and be done. But it is not flexible this way.

The proposal is to change type signatures to 

```haskell
fibonacci :: Num a => Int -> a
fibonacciPair :: Num a => Int -> (a, a)
lucas :: Num a => Int -> a
lucasPair :: Num a => Int -> (a, a)
generalLucas :: Num a => a -> a -> Int -> (a, a, a, a)
```

This change should be pretty mechanical; the only thing to deal with is `shiftL`, which should be replaced by addition. The main computation cost is caused by multiplications, any way.

This change is also more in line with `Math.NumberTheory.Recurrencies.Bilinear`, where all recurrent sequences are as polymorphic as possible.

**Comment by cartazio** [comment]
sounds good

we should make sure the standard specailizations are made available, which
should be simply a SPECIALIZE pragma in the source module?

**Comment by Bodigrim** [comment]
Absolutely.
