### ISSUE TITLE
New Chinese Remainder Module?

### ISSUE THREAD

**Issue by CarlEdman** [cartazio/arithmoi#69]
Congratulations on 0.6.0.0!  So much good stuff, so much stuff which I had already written and planned to contribute but never got around to!

Lest more of my efforts be wasted, let me start by offering an alternative implementation of the Chinese Remainder module.  It differs from the current implementation in the following points:

1. It uses the M.NT.Moduli.Class types which makes the interface more consistent and generally neater.  For example, the signature of `chineseRemainder` is `[SomeMod] -> Maybe SomeMod`.  So, for example, `chineseRemainder [3 \`modulo\` 4, 7 \`modulo\` 9, 0 \`modulo\` 5]' evaluates to `Just (115 \`modulo\` 180)`.  No longer mixing up which part of the pairs is the modulus, which the remainder, etc.

1. It correctly deals with `InfMod` constructor for `SomeMod`  It is interpreted to represent the congruence class consisting of just a single rational (I am not sure I understand the reasoning for having a Rational, rather than Integer representation?).  So, for example, `chineseRemainder [3 \`modulo\` 4, 7 \`modulo\` 9, 0 \`modulo\` 5, 295] == Just 295 % 1` and `chineseRemainder [3 \`modulo\` 4, 7 \`modulo\` 9, 0 \`modulo\` 5, 296] == Nothing`

1. Most importantly for my usage cases, it correctly handles the cases where the moduli are not pairwise co-prime, rather than always returning Nothing, even if the congruences could be fulfilled: `chineseRemainder [3 \`modulo\` 4, 7 \`modulo\` 6] = Just (7 \`modulo\` 12)`  I am not positive that the algorithm is optimal, but after running many thousands of quickChecks, I'm pretty sure it is correct.  As it only ever comes into play when the current implementation would just fail, I think even a suboptimal algorithm (if that is what it is), is an improvement.

```module ChineseRemainder where

import Control.Monad
import Data.Ratio
import Math.NumberTheory.Moduli.Class
import Math.NumberTheory.Primes.Factorisation

chineseRemainder :: [SomeMod] -> Maybe SomeMod
chineseRemainder (x:xs) = foldM chineseRemainder' x xs
chineseRemainder _ = Just (0 `modulo` 1)

chineseRemainder' :: SomeMod -> SomeMod -> Maybe SomeMod
chineseRemainder' x@(SomeMod x') y@(SomeMod y')
  | getMod x' == 1        = Just y
  | getMod y' == 1        = Just x
  | Just (SomeMod j) <- i = Just $ (xv+(yv-xv)*xm*getVal j) `modulo` (xn*yn)
  | (xv-yv) `mod` gm == 0 = chineseRemainder' (xv `modulo` xq) (yv `modulo` yq)
  | otherwise             = Nothing
  where
    xv = getVal x'
    xm = getMod x'
    xn = getNatMod x'

    yv = getVal y'
    ym = getMod y'
    yn = getNatMod y'

    i = invertSomeMod (xm `modulo` yn)

    gn = gcd xn yn
    gm = fromIntegral gn

    (xq, yq) = foldr enrich (xn `div` gn, yn `div` gn) $ factorise gm
    enrich (p',a) (xo, yo)
      | xo `mod` p == 0 = (xo*p^a, yo)
      | otherwise       = (xo, yo*p^a)
      where
        p = fromIntegral p'

chineseRemainder' x@(SomeMod x') y@(InfMod y')
  | denominator y' /= 1                       = Nothing
  | numerator y' `mod` getMod x' == getVal x' = Just y
  | otherwise                                 = Nothing

chineseRemainder' x@(InfMod _) y@(SomeMod _) = chineseRemainder' y x

chineseRemainder' x y
  | x == y    = Just x
  | otherwise = Nothing

prop_chineseRemainder' :: Integer -> Positive Integer -> Integer -> Positive Integer -> Bool
prop_chineseRemainder' xv (Positive xm) yv (Positive ym)
  | Just (SomeMod d) <- c = getMod d==l && [getVal d] == sols
  | otherwise             = null sols
  where
    l = lcm xm ym
    c = chineseRemainder' (xv `modulo` (fromIntegral xm)) (yv `modulo` (fromIntegral ym))
    sols = [i|i<-[0..l-1],(i-xv) `mod` xm==0,(i-yv) `mod` ym==0]
```

**Comment by Bodigrim** [comment]
Looks promising; I'll dig into it later this week. Thanks for contributing!

**Comment by Bodigrim** [comment]
Your proposal is very welcome: both refining of interface and dealing with non-coprime moduli are brilliant ideas. 

Could you please put your proposal into shape of Pull Request? If you do not want to mess with `git`, you can do it entirely from GitHub web interface. Click "Fork" button near the right top corner at https://github.com/cartazio/arithmoi and edit file by file, clicking by "Edit this file" (pencil icon on the right). Feel free to ask any questions. 

I think it is worth to separate and expose a subfunction with type signature `Mod m -> Mod n -> Maybe (Mod (m * n))`, throwing `Nothing` if `gcd m n > 1`, and to build `chineseRemainder'` atop. The former function may be useful by itself and offers better control over resources (for instance, in some scenarios user may prefer to invoke special factorisation routine, or handle non-coprime moduli completely different).

**Comment by CarlEdman** [comment]
Done.  I've added the new functions with a terminal s and deprecated, but preserved the old functions for backward compatibility.

Your suggestion regarding a `chineseRemainders2' :: Mod m -> Mod n -> Maybe (Mod (m * n))` is well taken.  I've not yet written it because I couldn't make it work, doubtlessly due to my imperfect understanding of the dependent type system.  I'll give it another try.  Maybe one could even come up with some sort of type magic to construct the type `Maybe (Mod (gcd m n))` to give the correct answer in all cases.

**Comment by Bodigrim** [comment]
Let us continue the discussion in #71.

**Comment by Bodigrim** [comment]
It is time to revive the issue. I have just stopped supporting GHC < 8.0, which means that one can use [timesNat](http://hackage.haskell.org/package/constraints-0.9.1/docs/Data-Constraint-Nat.html#v:timesNat) and [gcdNat](http://hackage.haskell.org/package/constraints-0.9.1/docs/Data-Constraint-Nat.html#v:gcdNat), which can be used to provide `KnownNat` instances as described [here](https://github.com/cartazio/arithmoi/pull/71#issuecomment-354658061). 

My API proposal is as follows:

1. A function, which takes `n1 :: Mod m1`, `n2 :: Mod m2`. If `m1` and `m2` are not coprime, it returns `Nothing`. Otherwise it returns `n :: Mod (m1 * m2)` such that `mod n m1 == n1` 
and `mod n m2 == n2`, similar to existing `chineseRemainder2`.

    ```haskell
    chineseMul :: (KnownNat m1, KnownNat m2) => Mod m1 -> Mod m2 -> Maybe (Mod (m1 * m2))
    ```

2. A more relaxed function, close in spirit to [chineseRemainders2](https://github.com/cartazio/arithmoi/pull/71/files#diff-0d440d9b8c70aba6643e77347d2925cdR87). This function returns `Nothing` only if there is no such `n :: Mod (Gcd m1 m2)` at all. It is desirable to do not call `factorise` internally, if possible. 

    ```haskell
    chineseGcd :: (KnownNat m1, KnownNat m2) => Mod m1 -> Mod m2 -> Maybe (Mod (Gcd m1 m2))
    ```

3. A function, which wraps arguments and result in `SomeMod`. This allows to use it in folds, like `foldlM chinese`. 

    ```haskell
    chinese :: SomeMod -> SomeMod -> Maybe SomeMod 
    ```
