### ISSUE TITLE
Benchmark Math.NumberTheory.GCD

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#80]
There are two modules, implementing very low-level algorithms for [GCD](https://en.wikipedia.org/wiki/Greatest_common_divisor): [Math.NumberTheory.GCD](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/GCD.hs) and [Math.NumberTheory.GCD.LowLevel](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/GCD/LowLevel.hs). I am wondering whether they are still faster than `gcd` in modern `base` (cf. #51 about `Math.NumberTheory.Powers.Integer`). It would be nice to benchmark them with `criterion`. 

Namely:

1. Is `binaryGCD` faster than `Prelude.gcd`?
2. Is `coprime` faster than `Prelude.gcd`?
3. Is `extendedGCD` faster than `GHC.Integer.GMP.Internals. gcdExtInteger`?
4. Or maybe are their specialised and unboxed counterparts from `Math.NumberTheory.GCD.LowLevel` worth a trouble?

**Comment by jgertm** [comment]
I started working on this [here](https://github.com/cartazio/arithmoi/pull/92)

**Comment by Bodigrim** [comment]
I took a closer look into `Prelude.gcd`. It is compiled into a direct call to GNU GMP library, so I do not think that any native Haskell implementation can beat its performance on average. So we should probably scrap `gcd` and `coprime` from `Math.NumberTheory.GCD` and remove `Math.NumberTheory.GCD.LowLevel` entirely.
