### ISSUE TITLE
Discrete logarithms

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#88]
Once #86 lands into master, it would be nice to implement any non-trivial (or even trivial one!) algorithm for computation of discrete logarithms. I do not know much about this field, but hopefully [wiki](https://en.wikipedia.org/wiki/Discrete_logarithm#Algorithms) could serve a good starting point.

**Comment by cartazio** [comment]
I fuzzily recall the pollard rho algorithm is one of the classics
