### ISSUE TITLE
Wrap output of splitIntoCoprimes into newtype

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#89]
Currently [splitIntoCoprimes](https://github.com/cartazio/arithmoi/blob/master/Math/NumberTheory/GCD.hs#L267) guarantees certain properties of its output, but still returns a plain `[(a, b)]`. Such return type is easily corruptible by other functions. It would be much better to return something like 

```haskell
newtype Coprimes a b = Coprimes (Map a b)
```

The interface should not expose `Coprimes` constructor outside. Here is a quick draft of API:

```haskell
instance Semigroup (Coprimes a b) where ...

instance Monoid (Coprimes a b) where ...

insert :: a -> b -> Coprimes a b -> Coprimes a b 

toList :: Coprimes a b -> [(a, b)]
```

---

Another vaguely related idea is to keep coprimes, which are known to be prime, separately. This can potentially speed up certain computations, especially with `Prefactored`. Like 

```haskell
data Coprimes a b = Coprimes (Map (Prime a) b) (Map a b)
```

**Comment by cartazio** [comment]
Style wise I like to use record fields to document what different positions
in a tuple mean. (One of my fave party tricks Is showing that you can mix
record and fast syntax.  Though that’s not relevant here ;) )
