### ISSUE TITLE
Change output of prime sieves from [Integer] to [Word]

### ISSUE THREAD

**Issue by Bodigrim** [cartazio/arithmoi#94]
Currently Eratosthenes sieves from `Math.NumberTheory.Primes.Sieve.Eratosthenes` output a list of `Integer` and operate internally on `Integer` and `Int`. This was reasonable historically, when x32 architecture was omnipresent. Nowadays it does not make much sense: Eratosthenes sieves consume far too much memory beyond 2^64 to be practical. 

That said, it would be more memory efficient to use `Int` or `Word` to represent generated primes. Since primes are unsigned, `Word` looks good. It would be even better to use newtype wrapper `Prm` from `Math.NumberTheory.Primes.Types`, but it may be deferred to a separate patch.

Another idea to achieve better backward compatibility: sieves can be parametrised by unsigned type of offset (`Word` or `Natural`) to support rare cases, when one would like to use them beyond 2^64.

**Comment by cartazio** [comment]
would it be better to use Word64? (or is there physical memory issues that
leak in?)

**Comment by Bodigrim** [comment]
`Word64` would be fine too, I think.

**Comment by Bodigrim** [comment]
I prepared a [branch](https://github.com/Bodigrim/arithmoi/tree/prime-sieves), which makes `primes` polymorphic by result type. There is still an issue, when an output type is finite. For example, `primes :: [Int8]` returns an infinite list of primes modulo 256 instead of a finite list of primes between 1 and 255.
